use ignug;
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('394','1','472','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('395','1','473','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('396','1','474','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('397','1','475','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('398','1','476','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('399','1','477','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('400','1','478','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('401','1','479','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('402','1','480','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('403','1','481','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('404','1','482','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('405','1','483','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('406','1','484','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('407','1','485','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('408','1','486','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('409','1','487','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('410','1','488','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('411','1','489','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('412','1','490','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('413','1','491','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('414','1','492','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('415','1','493','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('416','1','494','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('417','1','495','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('418','1','496','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('419','1','497','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('420','1','684','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('421','1','685','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('422','1','686','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('423','1','687','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('424','1','688','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('425','1','689','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('426','11','618','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('427','11','619','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('428','11','620','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('429','11','621','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('430','11','622','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('431','11','623','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('432','11','624','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('433','11','625','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('434','11','626','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('435','11','627','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('436','11','628','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('437','11','629','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('438','11','630','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('439','11','631','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('440','11','632','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('441','11','637','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('442','4','500','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('443','4','501','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('444','4','503','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('445','4','504','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('446','4','511','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('447','4','513','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('448','4','514','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('449','4','516','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('450','4','522','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('451','4','525','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('452','4','526','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('453','4','528','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('454','4','531','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('455','4','533','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('456','4','534','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('457','4','536','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('458','4','539','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('459','4','541','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('460','4','545','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('461','4','546','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('462','4','552','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('463','4','553','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('464','4','554','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('465','4','557','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('466','4','558','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('467','4','560','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('468','4','670','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('469','4','671','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('470','4','672','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('471','4','673','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('472','4','674','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('473','4','675','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('474','4','676','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('475','4','677','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('476','4','678','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('477','2','561','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('478','2','562','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('479','2','563','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('480','2','564','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('481','2','565','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('482','2','566','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('483','2','567','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('484','2','568','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('485','2','569','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('486','2','570','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('487','2','571','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('488','2','572','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('489','2','573','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('490','2','574','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('491','2','575','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('492','2','576','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('493','2','577','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('494','2','578','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('495','2','579','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('496','2','580','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('497','2','581','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('498','2','582','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('499','2','583','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('500','2','584','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('501','2','585','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('502','2','586','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('503','2','587','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('504','2','588','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('505','2','589','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('506','2','590','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('507','2','591','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('508','2','592','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('509','2','593','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('510','2','594','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('511','2','595','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('512','2','596','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('513','2','597','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('514','2','598','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('515','2','599','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('516','2','600','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('517','2','601','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('518','2','602','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('519','2','603','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('520','2','604','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('521','2','605','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('522','2','606','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('523','2','607','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('524','2','608','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('525','2','609','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('526','2','610','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('527','2','611','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('528','2','612','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('529','2','613','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('530','2','614','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('531','2','615','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('532','2','616','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('533','2','617','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('534','2','638','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('535','2','639','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('536','2','640','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('537','2','641','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('538','2','642','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('539','2','643','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('540','2','644','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('541','2','645','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('542','2','646','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('543','2','647','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('544','2','648','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('545','2','649','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('546','2','650','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('547','2','651','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('548','2','652','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('549','2','653','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('550','2','654','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('551','2','655','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('552','2','656','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('553','2','657','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('554','2','658','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('555','2','659','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('556','2','660','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('557','2','661','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('558','2','662','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('559','2','663','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('560','2','664','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('561','2','665','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('562','2','666','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('563','2','667','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('564','2','668','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES ('565','2','669','1','3','2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (986,3,697,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (987,3,698,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (988,3,699,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (989,3,700,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (990,3,701,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (991,3,702,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (992,3,703,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (993,3,704,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (994,3,705,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (995,3,706,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (996,3,707,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (997,3,708,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (998,3,709,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (999,3,710,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1000,3,711,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1001,3,712,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1002,3,713,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1003,3,714,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1004,3,715,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1005,3,716,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1006,3,717,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1007,3,718,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1008,3,719,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1009,3,720,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1010,3,721,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1011,3,722,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1012,3,723,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1013,3,724,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1014,3,725,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1015,3,726,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1016,3,727,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1017,3,728,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1018,3,729,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1019,3,730,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1020,3,731,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1021,3,732,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1022,3,733,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1023,3,734,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1024,3,735,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1025,3,736,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1026,3,737,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1027,3,738,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1028,3,739,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1029,3,740,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1030,3,741,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1031,3,742,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1032,3,743,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1033,3,744,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1034,3,745,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1035,3,746,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1036,3,747,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1037,3,748,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1038,3,749,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1039,3,750,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1040,3,751,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1041,3,752,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1042,3,753,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1043,3,754,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1044,3,755,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1045,3,756,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1046,3,757,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1047,3,758,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1048,1,759,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1049,1,760,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1050,1,761,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1051,1,762,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1052,1,763,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1053,1,764,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1054,1,765,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1055,1,766,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1056,4,767,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1057,4,768,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1058,4,769,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1059,4,770,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1060,4,771,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1061,4,772,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1062,4,773,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1063,4,774,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1064,4,775,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1065,4,776,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1066,4,777,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1067,4,778,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1068,4,779,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1069,4,780,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1070,4,781,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1071,4,782,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1072,4,783,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1073,4,784,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1074,4,785,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1075,4,786,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1076,4,787,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1077,4,788,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1078,4,789,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1079,4,790,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1080,4,791,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1081,4,792,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1082,4,793,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1083,4,794,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1084,4,795,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1085,4,796,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1086,4,797,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1087,4,798,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1088,4,799,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1089,4,800,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1090,4,801,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1091,4,802,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1092,4,803,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1093,4,804,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1094,4,805,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1095,4,806,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1096,4,807,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1097,4,808,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1098,4,809,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1099,11,810,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1100,11,811,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1101,11,812,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1102,11,813,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1103,11,814,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1104,11,815,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1105,11,816,1,3,'2018-04-04');
INSERT INTO Cupo (id,idJornadaCarrera, idPersona, idEstadoCupo, idPeriodoLectivo, fecha) VALUES (1106,11,817,1,3,'2018-04-04');

INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('477','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('477','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('477','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('477','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('478','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('478','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('478','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('478','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('479','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('479','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('479','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('479','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('480','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('480','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('480','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('480','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('481','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('481','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('481','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('481','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('482','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('482','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('482','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('482','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('483','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('483','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('483','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('483','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('484','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('484','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('484','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('484','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('485','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('485','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('485','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('485','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('486','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('486','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('486','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('486','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('487','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('487','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('487','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('487','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('488','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('488','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('488','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('488','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('489','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('489','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('489','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('489','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('490','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('490','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('490','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('490','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('491','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('491','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('491','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('491','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('492','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('492','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('492','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('492','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('493','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('493','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('493','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('493','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('494','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('494','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('494','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('494','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('495','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('495','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('495','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('495','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('496','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('496','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('496','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('496','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('497','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('497','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('497','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('497','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('498','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('498','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('498','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('498','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('499','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('499','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('499','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('499','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('500','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('500','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('500','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('500','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('501','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('501','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('501','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('501','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('502','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('502','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('502','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('502','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('503','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('503','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('503','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('503','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('504','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('504','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('504','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('504','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('505','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('505','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('505','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('505','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('506','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('506','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('506','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('506','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('507','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('507','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('507','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('507','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('508','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('508','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('508','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('508','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('509','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('509','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('509','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('509','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('510','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('510','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('510','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('510','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('511','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('511','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('511','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('511','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('512','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('512','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('512','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('512','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('513','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('513','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('513','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('513','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('514','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('514','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('514','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('514','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('515','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('515','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('515','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('515','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('516','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('516','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('516','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('516','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('517','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('517','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('517','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('517','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('518','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('518','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('518','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('518','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('519','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('519','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('519','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('519','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('520','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('520','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('520','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('520','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('521','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('521','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('521','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('521','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('522','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('522','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('522','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('522','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('523','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('523','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('523','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('523','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('524','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('524','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('524','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('524','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('525','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('525','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('525','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('525','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('526','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('526','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('526','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('526','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('527','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('527','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('527','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('527','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('528','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('528','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('528','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('528','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('529','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('529','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('529','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('529','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('530','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('530','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('530','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('530','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('531','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('531','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('531','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('531','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('532','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('532','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('532','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('532','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('533','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('533','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('533','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('533','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('534','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('534','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('534','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('534','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('535','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('535','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('535','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('535','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('536','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('536','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('536','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('536','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('537','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('537','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('537','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('537','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('538','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('538','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('538','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('538','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('539','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('539','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('539','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('539','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('540','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('540','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('540','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('540','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('541','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('541','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('541','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('541','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('542','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('542','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('542','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('542','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('543','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('543','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('543','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('543','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('544','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('544','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('544','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('544','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('545','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('545','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('545','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('545','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('546','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('546','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('546','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('546','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('547','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('547','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('547','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('547','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('548','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('548','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('548','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('548','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('549','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('549','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('549','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('549','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('550','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('550','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('550','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('550','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('551','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('551','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('551','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('551','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('552','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('552','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('552','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('552','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('553','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('553','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('553','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('553','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('554','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('554','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('554','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('554','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('555','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('555','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('555','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('555','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('556','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('556','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('556','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('556','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('557','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('557','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('557','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('557','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('558','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('558','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('558','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('558','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('559','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('559','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('559','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('559','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('560','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('560','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('560','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('560','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('561','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('561','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('561','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('561','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('562','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('562','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('562','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('562','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('563','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('563','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('563','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('563','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('564','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('564','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('564','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('564','34');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('565','31');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('565','32');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('565','33');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('565','34');

INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('426','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('427','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('428','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('429','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('430','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('431','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('432','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('433','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('434','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('435','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('436','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('437','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('438','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('439','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('440','56');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','51');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','52');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','53');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','54');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','55');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('441','56');

INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('442','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('442','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('442','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('442','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('442','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('443','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('443','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('443','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('443','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('443','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('444','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('444','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('444','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('444','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('444','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('445','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('445','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('445','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('445','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('445','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('446','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('446','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('446','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('446','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('446','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('447','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('447','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('447','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('447','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('447','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('448','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('448','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('448','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('448','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('448','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('449','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('449','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('449','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('449','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('449','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('450','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('450','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('450','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('450','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('450','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('451','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('451','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('451','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('451','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('451','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('452','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('452','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('452','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('452','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('452','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('453','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('453','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('453','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('453','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('453','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('454','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('454','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('454','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('454','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('454','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('455','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('455','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('455','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('455','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('455','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('456','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('456','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('456','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('456','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('456','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('457','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('457','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('457','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('457','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('457','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('458','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('458','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('458','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('458','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('458','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('459','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('459','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('459','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('459','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('459','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('460','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('460','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('460','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('460','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('460','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('461','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('461','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('461','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('461','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('461','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('462','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('462','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('462','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('462','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('462','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('463','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('463','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('463','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('463','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('463','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('464','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('464','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('464','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('464','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('464','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('465','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('465','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('465','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('465','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('465','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('466','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('466','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('466','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('466','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('466','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('467','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('467','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('467','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('467','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('467','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('468','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('468','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('468','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('468','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('468','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('469','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('469','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('469','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('469','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('469','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('470','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('470','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('470','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('470','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('470','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('471','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('471','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('471','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('471','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('471','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('472','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('472','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('472','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('472','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('472','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('473','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('473','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('473','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('473','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('473','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('474','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('474','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('474','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('474','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('474','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('475','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('475','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('475','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('475','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('475','39');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('476','35');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('476','36');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('476','37');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('476','38');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('476','39');

INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('394','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('395','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('396','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('397','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('398','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('399','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('400','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('401','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('402','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('403','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('404','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('405','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('406','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('407','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('408','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('409','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('410','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('411','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('412','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('413','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('414','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('415','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('416','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('417','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('418','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('419','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('420','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('421','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('422','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('423','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('424','6');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','1');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','2');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','3');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','4');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','5');
INSERT INTO AsignaturaCupo (idCupo, idAsignatura) VALUES ('425','6');
