#Lista de Matriculados Asignatura, Carrera, Jornada
SELECT Carrera.nombre, Jornada.descripcion, Asignatura.idPeriodoAcademico, Asignatura.nombre, Persona.identificacion, Persona.nombre1, Persona.nombre2, Persona.apellido1, Persona.apellido2, Persona.correoElectronicoInstitucional, Persona.correoElectronicoPersonal FROM Matricula INNER JOIN Persona ON Matricula.idPersona = Persona.id INNER JOIN Carrera ON Carrera.id = Matricula.idCarrera INNER JOIN Jornada ON Jornada.id = Matricula.idJornada INNER JOIN MatriculaAsignatura ON Matricula.id = MatriculaAsignatura.idMatricula INNER JOIN Asignatura ON MatriculaAsignatura.idAsignatura = Asignatura.id WHERE Matricula.idPeriodoLectivo = 3;
#Matriculados por carrera, instituto
SELECT a.Instituto, a.Carrera, count(a.Estudiantes) as 'cuenta' FROM (SELECT DISTINCT Instituto.descripcion as 'Instituto', Carrera.nombre as 'Carrera', Persona.id as 'Estudiantes' FROM Persona INNER JOIN Matricula ON Matricula.idPersona = Persona.id INNER JOIN Carrera ON Carrera.id = Matricula.idCarrera INNER JOIN Instituto ON Carrera.idInstituto = Instituto.id WHERE Matricula.idPeriodoLectivo = 3) a GROUP BY a.Instituto, a.Carrera ORDER BY a.Instituto, a.Carrera;
#Matriculados por carrera, instituto, jornada
SELECT a.Instituto, a.Carrera, a.Jornada, count(a.Estudiantes) as 'cuenta' FROM (SELECT DISTINCT Instituto.descripcion as 'Instituto', Carrera.nombre as 'Carrera', Jornada.descripcion as 'Jornada', Persona.id as 'Estudiantes' FROM Persona INNER JOIN Matricula ON Matricula.idPersona = Persona.id INNER JOIN Carrera ON Carrera.id = Matricula.idCarrera INNER JOIN Instituto ON Carrera.idInstituto = Instituto.id INNER JOIN Jornada ON Jornada.id = Matricula.idJornada WHERE Matricula.idPeriodoLectivo = 3) a GROUP BY a.Instituto, a.Carrera, a.Jornada ORDER BY a.Instituto, a.Carrera, a.Jornada;
#Matriculados por carrera, instituto, jornada Periodo Acedmico
SELECT a.Instituto, a.Carrera, a.Jornada, a.PeriodoAcademico, count(a.Estudiantes) as 'cuenta' FROM (SELECT DISTINCT Instituto.descripcion as 'Instituto', Carrera.nombre as 'Carrera', Jornada.descripcion as 'Jornada', Asignatura.idPeriodoAcademico as 'PeriodoAcademico', Persona.id as 'Estudiantes' FROM Persona INNER JOIN Matricula ON Matricula.idPersona = Persona.id INNER JOIN Carrera ON Carrera.id = Matricula.idCarrera INNER JOIN Instituto ON Carrera.idInstituto = Instituto.id INNER JOIN Jornada ON Jornada.id = Matricula.idJornada INNER JOIN MatriculaAsignatura ON MatriculaAsignatura.idMatricula = Matricula.id INNER JOIN Asignatura ON Asignatura.id = MatriculaAsignatura.idAsignatura WHERE Matricula.idPeriodoLectivo = 3) a GROUP BY a.Instituto, a.Carrera, a.Jornada, a.PeriodoAcademico ORDER BY a.Instituto, a.Carrera, a.Jornada, a.PeriodoAcademico;
#Estudiantes Solicitud de matricula emitida no matriculados
SELECT Carrera.nombre, Jornada.descripcion, p.* FROM (SELECT DISTINCT Cupo.id as idCupo, Persona.id as idEstudiante, Persona.identificacion, Persona.nombre1, Persona.nombre2, Persona.apellido1, Persona.apellido2, Persona.telefonoCelular, Persona.telefonoDomicilio, Persona.correoElectronicoPersonal, Persona.correoElectronicoInstitucional FROM Persona INNER JOIN Cupo ON Persona.id = Cupo.idPersona INNER JOIN SolicitudMatricula ON SolicitudMatricula.idPersona = Cupo.idPersona WHERE SolicitudMatricula.idPersona NOT IN (SELECT Matricula.idPersona FROM Matricula WHERE Matricula.idPeriodoLectivo = 3) AND SolicitudMatricula.idPeriodoLectivo = 3) p INNER JOIN Cupo ON Cupo.id = p.idCupo INNER JOIN JornadaCarrera ON Cupo.idJornadaCarrera = JornadaCarrera.id INNER JOIN Carrera ON JornadaCarrera.idCarrera = Carrera.id INNER JOIN Jornada ON Jornada.id = JornadaCarrera.idJornada WHERE Cupo.idPeriodoLectivo = 3;
#Solicitud de matricula emitida no matriculados
SELECT a.Carrera, a.Jornada, count(a.idCupo) as cuenta FROM (SELECT Carrera.nombre as Carrera, Jornada.descripcion as Jornada, p.* FROM (SELECT DISTINCT Cupo.id as idCupo, Persona.id as idEstudiante, Persona.identificacion, Persona.nombre1, Persona.nombre2, Persona.apellido1, Persona.apellido2, Persona.telefonoCelular, Persona.telefonoDomicilio, Persona.correoElectronicoPersonal, Persona.correoElectronicoInstitucional FROM Persona INNER JOIN Cupo ON Persona.id = Cupo.idPersona INNER JOIN SolicitudMatricula ON SolicitudMatricula.idPersona = Cupo.idPersona WHERE SolicitudMatricula.idPersona NOT IN (SELECT Matricula.idPersona FROM Matricula WHERE Matricula.idPeriodoLectivo = 3) AND SolicitudMatricula.idPeriodoLectivo = 3) p INNER JOIN Cupo ON Cupo.id = p.idCupo INNER JOIN JornadaCarrera ON Cupo.idJornadaCarrera = JornadaCarrera.id INNER JOIN Carrera ON JornadaCarrera.idCarrera = Carrera.id INNER JOIN Jornada ON Jornada.id = JornadaCarrera.idJornada WHERE Cupo.idPeriodoLectivo = 3) a GROUP BY a.Carrera, a.Jornada ORDER BY a.Carrera, a.Jornada;
#Estudiantes Cupo asignado sin emitir solitud ni matriculados
SELECT Carrera.nombre as Carrera, Jornada.descripcion as Jornada, p.* FROM (SELECT * FROM Cupo WHERE Cupo.idPersona NOT IN (SELECT SolicitudMatricula.idPersona FROM SolicitudMatricula)) p INNER JOIN JornadaCarrera ON JornadaCarrera.id = p.idJornadaCarrera INNER JOIN Carrera ON JornadaCarrera.idCarrera = Carrera.id INNER JOIN Jornada ON JornadaCarrera.idJornada = Jornada.id WHERE p.idPersona NOT IN (SELECT Matricula.idPersona FROM Matricula) AND p.idPeriodoLectivo = 3;
#Cupo asignado sin emitir solitud ni matriculados
SELECT a.Carrera, a.Jornada, count(a.id) FROM (SELECT Carrera.nombre as Carrera, Jornada.descripcion as Jornada, p.* FROM (SELECT * FROM Cupo WHERE Cupo.idPersona NOT IN (SELECT SolicitudMatricula.idPersona FROM SolicitudMatricula)) p INNER JOIN JornadaCarrera ON JornadaCarrera.id = p.idJornadaCarrera INNER JOIN Carrera ON JornadaCarrera.idCarrera = Carrera.id INNER JOIN Jornada ON JornadaCarrera.idJornada = Jornada.id WHERE p.idPersona NOT IN (SELECT Matricula.idPersona FROM Matricula) AND p.idPeriodoLectivo = 3) a GROUP BY a.Carrera, a.Jornada ORDER BY a.Carrera, a.Jornada;